# Generated by Django 4.2.4 on 2023-08-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_burguer',
            name='tipo',
            field=models.CharField(default='Em produção', max_length=20),
        ),
    ]
